project_id = "jwjmseeyjemfwgyizumk"

[functions.enviar-whatsapp]
verify_jwt = false

[functions.enviar-apresentacao-msg]
verify_jwt = false

[functions.gerar-flyer]
verify_jwt = false

[functions.notificar-ausencia-kids]
verify_jwt = false

[functions.relatorio-mensal-kids]
verify_jwt = false

[functions.lembrete-culto-kids]
verify_jwt = false

[functions.rekognition-faces]
verify_jwt = false

[functions.criar-usuario-membro]
verify_jwt = false

[functions.get-member-sensitive-data]
verify_jwt = false

[functions.atualizar-senha-usuario]
verify_jwt = false

[functions.notificar-mudanca-pendente]
verify_jwt = false

[functions.processar-aprovacao-mudanca]
verify_jwt = false

[functions.notificar-cadastro-alteracao]
verify_jwt = false

[functions.gerar-cr-express]
verify_jwt = false

[functions.enviar-cr-express]
verify_jwt = false

[functions.finalizar-evento]
verify_jwt = false

[functions.sync-teologia-alunos]
verify_jwt = false

[functions.api-teologia-pagamentos]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.processar-fila-whatsapp]
verify_jwt = false

[functions.agenda-ical]
verify_jwt = false

[functions.wasender-webhook]
verify_jwt = false

[functions.contagem-culto]
verify_jwt = false
